### ISSUE TITLE
Date attribute exists

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback-datasource-juggler#592]
I have declared a date field in the model:

```
    "availableToDate": {
        "type": "date"
    },
```

and then tried to make a find with an or condition:

```
or: [{
          availableToDate: {gte: today}
        }, {
          availableToDate: {exists: false}
        }, {
          availableToDate: null
        }],
```

 and i get following error:

```
Error: Invalid date: [object Object]
    at DateType (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:929:11)
    at Function.DataAccessObject._coerce (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1082:15)
    at Function.DataAccessObject._coerce (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:982:16)
    at Function.DataAccessObject._normalize (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:922:8)
    at Function.find (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1184:10)
    at Object.eval [as forward] (eval at recompile (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:237:15), <anonymous>:4:32)
    at Function.find (eval at wrap (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:193:20), <anonymous>:3:21)
    at Function.Product.findByCategory (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/common/models/product.js:31:13)
    at SharedMethod.invoke (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:207:25)
    at HttpContext.invoke (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:335:12)
```

Is this a bug in the validation?

**Comment by raymondfeng** [comment]
It seems the Date type validation is not happy with `null`, which is a bug. Can you submit a patch?

**Comment by kuskov** [comment]
@raymondfeng i was just testing it out and unfortunately don't have a fix for that

**Comment by kblcuk** [comment]
Probably related? https://github.com/strongloop/loopback/issues/1009#issuecomment-100921816

**Comment by kuskov** [comment]
Is there a fix already for this "exists" problem with date? @raymondfeng

**Comment by bajtos** [comment]
@kuskov Could you please submit a pull request and include tests to demonstrate that the proposed solution works as intended? You can take a look at #130 for inspiration.

**Comment by kuskov** [comment]
@bajtos unfortunately i don't really know how all this pull request/contributing stuff works...

**Comment by bajtos** [comment]
@kuskov don't worry, we'll help you. Start by reading my [Git Intro](https://gist.github.com/bajtos/27e3d1545a053d22015b), it should set you up for making your first contribution. Let me know if there is anything not clear enough, so that I can explain in more detail.

**Comment by kuskov** [comment]
@bajtos i have fetched the fork for me, changed the file and pushed it to master on the fork. Somehow i don't understand what to do next?

**Comment by bajtos** [comment]
@kuskov create a feature branch, it will make your life much easier. Starting on master:

```js
# create feature branch 
git checkout -b fix-date-exists
# push to the server
git push -u origin fix-date-exists
# switch back to master
git checkout master
# reset back to the original revision from upstream
git reset --hard HEAD^
# force-push to overwrite the history
git push -f
```

Once you have that done, open https://github.com/kuskov/loopback-datasource-juggler in your browser, you should see a white stripe suggesting you to submit a pull request.

**Comment by tsanjoto** [comment]
any new updates on this issue?

**Comment by mamartins** [comment]
yeah news on this PR would be great

**Comment by dhmlau** [comment]
I believe we've fixed it in PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1339
@ekussberg , could you please verify?  If you're good with the fix, we can close this issue.  Thanks.

**Comment by dhmlau** [comment]
Closing this since we think it's fixed in PR #1339.  If you still encounter this problem, please reopen.  Thanks.

**Comment by daankets** [comment]
This issue is still not fixed using version 3.12.0 of the datasource juggler.

Upon using a query like this:
```
{where: {someDateField: {exists: false}}}
```

Loopback still productes the `Error: Invalid date: [object Object]` error. This, combined with the lack of a 'not' operator makes it impossible to query for documents that do not have a certain date field set.

**Comment by bajtos** [comment]
@daankets thank you for the comment, I am reopening this issue then. Would you like to contribute the fix yourself?

**Comment by daankets** [comment]
I worked around this now inserting a boolean attribute using observe(“before save”). I didn’t have the time to look at this in-depth. But I might have a look next week.

With kind regards

Daan Kets
Managing Partner
Delta Source Belgium

On 5 Oct 2017, 13:35 +0200, Miroslav Bajtoš <notifications@github.com>, wrote:
> @daankets thank you for the comment, I am reopening this issue then. Would you like to contribute the fix yourself?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
*Disclaimer*
This message is *confidential* and only intended for the originally 
intended recipient(s). It may also be privileged or otherwise protected by 
work product immunity or other legal rules. *If you think you have received 
this message by mistake*, please let us know by e-mail reply and delete it 
from your system; you must not copy this message or disclose its contents 
to anyone other than the intended recipients.

**Comment by daankets** [comment]
@0candy This is still an issue today. If you are using MongoDB at least, you can not query using the exists operator on a date field.

```
{where: {someDateField: {exists:true}}} ==> Error: Invalid date: [object Object]
```

**Comment by sigalor** [comment]
@bajtos I am still experiencing this issue with MongoDB in Loopback 4 as well. Any updates on this in the last few years?
