### ISSUE TITLE
Scope didn't  work when use include(HasOne)

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback-datasource-juggler#594]
I  have model like this:

modelA: {
  "relation": {
    "bs": {
      "type": "hasOne",
      "model": "B",
      "foreignKey": "aId",
      "scope": {
        "where": {
          "kind": "b"
        }
      }
    },
    "cs": {
      "type": "hasOne",
      "model": "B",
      "foreignKey": "aId",
      "scope": {
        "where": {
          "kind": "c"
        }
      }
    }
  }
}   

when I get  an instance of A  by method "findById", I used A.include([result], ['bs','cs'], cb)}, and the result wasn't I want. In its bs, cs relation  was the same instance . I used juggler 2.27.0.
I tried it in 2.26.4, it is ok.
Is it a bug in 2.27.0?

**Comment by raymondfeng** [comment]
It's a possible regression from https://github.com/strongloop/loopback-datasource-juggler/commit/d009557a76cc8fe39314c2c1f1b4cdfe2520b4e2.

**Comment by raymondfeng** [comment]
Please try 2.27.1. It should have been fixed now.

**Comment by seriousben** [comment]
We are running 2.27.1 and definitely seeing a problem still, using some
nested includes and scopes. Seem to return non deterministic data.

**Comment by raymondfeng** [comment]
Can you provide a simple test case? We would like to include it to the test suite.

**Comment by seriousben** [comment]
Sure give me a few days.

**Comment by Spark-star** [comment]
THX, it works

2015-05-18 8:17 GMT+08:00 Benjamin Boudreau <notifications@github.com>:

> Sure give me a few days.
