### ISSUE TITLE
Fetching relating model crash app since version 2.39.0

### ISSUE THREAD

**Issue by jgpacheco** [strongloop/loopback-datasource-juggler#726]
I recently update my project dependencies, 'loopback-datasource-juggler' between them, and now my app crash when i try to fetch a related model through an 'owner model'. 

Let me explain better the situation. I have a model A that is related with model B ( 'referencesMany' relation type, i am using mongoDB as my backend database ), and when i try to do something like this using the REST API: modelA/{id}/modelsB or modelAInstance.modelsB() using the Node API, and the result is an empty list, my app crash with this message: 

**node.js:407**
        **callback();**
        **^**

**TypeError: callback is not a function**
    **at doNTCallback0 (node.js:407:9)**
    **at process._tickDomainCallback (node.js:377:13)**
    **at process.<anonymous> (../node_modules/async-listener/index.js:19:15)**

That only happen when the result is an empty list and in versions 2.39.0 and after. I had to downgrade my 'loopback-datasource-juggler' to 2.38.0 version to get my app functional again.

**Comment by raymondfeng** [comment]
Can you provide an isolated test project on github?

**Comment by jgpacheco** [comment]
I will do that in the next days, thanks for the quick answer.

**Comment by jgpacheco** [comment]
Looks like this was resolved in version 2.41.0:
    *findByIds would fail when an array of 0 length was passed as its first argument (James Cooke)*

Here is my isolated test project for reference: [Test project] (https://github.com/jgpacheco/loopback-test)

**Comment by jannyHou** [comment]
I am afraid the error still exist.
```
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
internal/process/next_tick.js:67
      callback();
      ^

TypeError: callback is not a function
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at process.fallback (/Users/jannyhou/lb/triage/loopback-test/node_modules/async-listener/index.js:457:15)
```

Tried with both mongodb and memory. I label it as a bug.

**Comment by sirnornur** [comment]
PS: it will work fine if the connected database table is empty. To reproduce there should be some data in database table and we fetch data, e.g. using `find()`.

**Comment by dhmlau** [comment]
Since the latest 2.x juggler version is 2.54.0 and last comment being almost 2 years ago, I'm closing this issue. 
@siddhipai @gpacheco, if you see encounter this issue, please ping here or open a new issue. Thanks.
